#!/bin/sh
set -eu
SOURCE_DIR="$(dirname "$0")"
MICROKIT_DIR="$SOURCE_DIR"/../../microkit
DOCKER_IMAGE_NAME=makatea-project/microkit-sdk-builder
set -x
cp -f "$MICROKIT_DIR"/requirements.txt "$SOURCE_DIR"
exec docker build --pull -t "$DOCKER_IMAGE_NAME" "$SOURCE_DIR"
