#!/bin/sh
set -eu
topdir="$(realpath "$(dirname "$0")/../..")"
mkdir -p "$topdir"/.cache/cargo
exec docker run  -it --rm                                       \
                 --volume "$topdir"/.cache:"$HOME"/.cache       \
                 --volume "$topdir":"$topdir"                   \
                 --workdir "$(pwd)"                             \
                 microkit-workspace                             \
                 "$@"
